AlgebraicJulia/Decapodes.jl

Project.toml
src/Diagrams.jl
src/Examples.jl
src/Schedules.jl
test/Decapodes.jl
test/Examples.jl

This PR adds a `@decapode` wrapper for the `@free_diagram` macro which handles projections for addition and functions with multiple inputs. This also supports equations which have composed expressions on both sides. 
This PR also removes AlgebraicPetri as a dependency, and resolves Issues #9 and #8
Following are some examples of supported uses of this macro.
```julia
@present DiffusionSpace2D(FreeExtCalc2D) begin
X::Space
k::Hom(Form1(X), Form1(X)) # diffusivity of space, usually constant (scalar multiplication)
proj₁_⁰⁰₀::Hom(Form0(X) ⊗ Form0(X), Form0(X))
proj₂_⁰⁰₀::Hom(Form0(X) ⊗ Form0(X), Form0(X))
sum₀::Hom(Form0(X) ⊗ Form0(X), Form0(X))
prod₀::Hom(Form0(X) ⊗ Form0(X), Form0(X))
end
Diffusion = @decapode DiffusionSpace2D begin
C::Form0{X}
⋆₀⁻¹{X}(dual_d₁{X}(⋆₁{X}(k(d₀{X}(C))))) == …
```

Adds @decapode Wrapper Macro

---

Project.toml
src/Decapodes.jl
src/Diagrams.jl
src/Examples.jl
src/PetriNets.jl
src/Schedules.jl
test/Decapodes.jl
test/Examples.jl
test/PetriNets.jl
test/runtests.jl

This PR adds interop tooling with AlgebraicPetri by converting a LabelledReactionNet into a Decapode under the law of mass-action.

Added interop tooling for PetriNets into Decapods

---

src/OpenDiagrams.jl

ExtCalc2D was renamed to ThExtCalc2D for Catlabv0.14 consistency.

Fix for Catlabv0.14.X

---

Artifacts.toml
src/Decapodes2/meshes.jl
test/Decapodes2/meshes.jl

Closes #58 
I have implemented mesh loading based on singleton types, with accompanying tests.
However, `export`ing a `loadmesh(meshkey::AbstractMeshKey)` is a little confusing.
I believe progress may go quicker on this issue if discussed in this PR, rather than me poring through the Julia manual alone.

Mesh artifacts and mesh loading

---

Artifacts.toml
src/Decapodes2/decapodes.jl
src/Decapodes2/meshes.jl
test/Decapodes2/meshes.jl

Closes #68 
We kept the old tarball so as not to break any code on old commits that is relying on the previous url.
The unit icospheres are made available via:
```julia
loadmesh(UnitIcosphere1())
loadmesh(UnitIcosphere2())
loadmesh(UnitIcosphere3())
loadmesh(UnitIcosphere4())
loadmesh(UnitIcosphere5())
```

Add icospheres of many subdivisions

---

src/Decapodes2/decapodeacset.jl
src/Decapodes2/decapodes.jl
src/Decapodes2/simulation.jl
test/Decapodes2/multiscalearrays.jl
test/Decapodes2/runtests.jl
test/Decapodes2/simulation.jl

The operation of scaling by a constant is so ubiquitous that we need to handle it directly rather than relying on the previous encoding of constants as "the action of the constant on a vector". This PR adds support for constants, which are entries in the parameter named tuple that do not depend on time and Parameters which are parameters that do depend on time.

Handle material properties as parameters instead of operators

---

src/Diagrams.jl

In Catlab version 0.14.10, the `free` keyword which distinguishes free from non-free diagrams is now a keyword given to the `AST.Diagram` constructor. Previously, this keyword was given to the diagram parsing function itself. This change broke the old decapodes parsing code when users update from v0.14.9.
This branch updates the old `src/Diagrams.jl` code to use this new parsing scheme. All tests pass.
Since this involves updating Catlab, this pull request is priority number one to get reviewed and merged for this project @jpfairbanks

Use Catlabv0.14.10 diagram parsing scheme

---

Project.toml
src/Decapodes2/decapodeacset.jl
src/Decapodes2/decapodes.jl
test/Decapodes2/diag2dwd.jl
test/runtests.jl

Currently, Decapodes compilation does not include any type inference stage, nor does it support function overloading, except for the `+` operator.
Type inference is useful for the reasons it is useful in programming. Further, it will let us support in the future the ability to use variables without declaring them.
Function overloading is useful for the reasons it is useful in programming. Further, it lets users write their Exterior Calculus equations in the format they appear in scientific papers, i.e. without subscripting their operators like `d` and hodge star with the type of the argument.
Both these techniques are being implemented in this pull request because they can both be performed using the same rewrite rules strategy via `AlgebraicRewriting.jl`.

Type inference and overloading resolution via rewrites

---

src/Decapodes2/decapodeacset.jl

Checks for uninitialized attributes in ACSets now must consider whether the given attribute is `nothing`.
This pull request checks for this condition when initializing intermediate variable names.

Update for Catlab v0.14.14

---

src/Decapodes2/simulation.jl

Using `Catlab.Programs` can sometimes cause naming conflicts, because `Catlab.Programs.GenerateJuliaPrograms` and this project both define a function `compile`.
Renaming `compile` to `compile_decapode` was considered, but since these functions are similar, it seems best to `import Catlab.Programs.GenerateJuliaPrograms: compile`.

Import compile from Catlab.Programs

---

src/Decapodes2/visualization.jl

Currently, the visualization code expects that edge labels are Symbols. During visualization, these Symbols are converted to Strings.
However, the types of such quantities in Decapodes read-in from JSON files are Strings.
So - without overhauling the visualization code - I implement a fix which relies on multiple dispatch to not "greedily" convert Symbols to Strings when assigning edge labels.

Do not convert edge labels that are already Strings

---

docs/make.jl
docs/src/ice_dynamics.md
docs/src/index.md
examples/brusselator/brusselator.jl
examples/climate/budyko_sellers.jl
examples/climate/nonhydrostatic_buoyancy.jl
examples/climate/shallow_ice.jl
src/decapodeacset.jl
src/simulation.jl
test/diag2dwd.jl

This PR introduces an ice model based on Halfar's "On the Dynamics of Ice Sheets". (1981).
We also update the Budyko-Sellers model to demonstrate composition.
There is also a fix to type inference of summations in this PR.
Ice height is initialized as an upwards parabola centered at (0,0).

Ice Dynamics

---

docs/make.jl
docs/src/budyko_sellers_halfar.md
examples/climate/budyko_sellers.jl
examples/climate/budyko_sellers_halfar.jl
examples/climate/shallow_ice.jl

This PR composes the Budyko-Sellers 1D energy-balance climate model with the Halfar model of glacial dynamics.
We wish to demonstrate an Decapodes multiphysics composition in which "the coupling occurs in the bulk... through source terms or constitutive relations that are active in the overlapping domains of the individual components" as described by Keyes et al. in their survey "Multiphysics simulations: Challenges and opportunities"[1] . Keyes et al. note that there are in fact many classifications of multiphysics, although in practice this first one is the one that most people refer to.
We do so with the composition pattern:
In our composition, Halfar's A is computed at each time-step according to the temperature T at each point on the domain. The chosen formula is inspired by the …

Compose Budyko-Sellers with Halfar

---

examples/chemistry/brusselator_teapot.jl

Most examples given at this point occur on simple domains such as the unit square, the unit sphere, the unit line, and so on.
To demonstrate flexibility of Decapodes simulations to non-trivial meshes, we demonstrate the Brusselator Decapode on the classic “teapot” mesh popular in the field of computer graphics.
Note that this mesh is rather large, so for faster runtimes one can use one of the other meshes in the main Brusselator example.
https://www.cise.ufl.edu/~luke.morris/imgs/brusselator_teapot.gif

Add example of physics on non-trivial domain

---

src/Decapodes.jl
src/decapodeacset.jl
test/diag2dwd.jl
test/rewrite.jl

Close #134 
Currently, when constructing Decapodes, tangent variables are always renamed as the variable they depend on appended with a dot.
E.g. `D == \partial\_t(C)` creates a Decapode with two variables named `C\dot` and `C`.
This strategy was chosen by default since users sometimes only describe TVars in terms of their relation to other quantities. E.g. in `\partial\_t(Foo) == Bar(Buzz)`, the quantity `\partial\_t(Foo)` is never given a human-legible name. So defaulting to `Foo\dot` is appropriate.
This is, of course, always fine from a compilation aspect, since the generated program is name-agnostic.
But, this can seriously impact usability. If a user has created a Decapode, and has given a TVar a human-readable name, then they expect to be able to refer to the TVar by that when …

Do not aggressively apply dot

---

docs/src/overview.md

`overview.md` previously used the `DiagonalHodge`. In the new docs, `GeometricHodge` was swapped in its place. This normally should not result in drastically different behavior. However, the way that `periodic_mesh` is implemented alongside a `point_map` means that calculations inside `GeometricHodge` will introduce artifacting where this periodic mesh is stitched together.

Use diagonal hodge in docs overview

---

examples/diff_adv/burger.jl

Closes #100 
Parts of this example were pair-programmed with @GeorgeR227 .
This PR uploads an example implementation of Burger's Equation as a Decapode in the 1D DEC.
This implementation re-uses Advection, Diffusion, and Superposition component Decapodes from the Advection-Diffusion example in the documentation. These components are composed with a Decapode implementing the Lie derivative.
We demonstrate some dynamics given an initial normal distribution.

Add Burger's Equation Decapode

---

examples/climate/budyko_sellers.jl
src/Decapodes.jl
src/simulation.jl
test/simulation.jl

@ChrisRackauckas, I added some fixes for #171

Using PreallocationTools.jl

---

src/Decapodes.jl
test/diag2dwd.jl

Anyone who uses `LinearAlgebra` and `Catlab` will receive a warning about `\cdot` being defined by both packages.
The particular warning generated by `Decapodes` in issue #157 can be avoided by removing some unnecessary `import`s from `Catlab.Theories`.

Remove Catlab.Theories imports

---

src/operators.jl
test/simulation.jl

Inverse Hodge 1 for Diagonal was mistakenly checking for AbstractDeltaDualComplex2D when it should work for either 1D or 2D. Thus it now only checks for HasDeltaSet.

Fixed Inv_Hodge_1 bug

---

docs/Project.toml
docs/src/bc_debug.md
docs/src/budyko_sellers_halfar.md
docs/src/cism.md
docs/src/grigoriev.md
docs/src/ice_dynamics.md
docs/src/overview.md

The most recent commit fixed the AxisAspect deprecation. This branch will be merged on fixing the remaining issues.

Update to Latest CairoMakie

---

src/simulation.jl
test/simulation.jl

Added a new infer/resolve cycle before changing to compiler types. Also added exponents to the assumed _ops, letting Julia define this operation itself without need for a generate function entry. Fixes issue #221.

Fixed problems with Constant typing

---

test/simulation.jl

Test allocations in simple simulations

---

docs/src/ascii.md
docs/src/bsh/budyko_sellers_halfar.md
docs/src/ice_dynamics/ice_dynamics.md
examples/climate/budyko_sellers_halfar.jl
examples/diff_adv/cht.jl
examples/diff_adv/cht_cuda.jl
ext/DecapodesCUDAExt.jl
src/operators.jl
src/simulation.jl

Use upstreamed averaging operator

---

ext/DecapodesCUDAExt.jl
src/Decapodes.jl
src/operators.jl
src/simulation.jl
test/runtests.jl
test/simulation.jl
test/simulation_core.jl

This PR is meant to clean up the compiler to ready it for larger refactors to come.

Smaller compiler refactoring

---

examples/chemistry/cahn_hilliard_cuda_32.jl

This example is meant mainly for stress testing our code optimization for CUDA. As we accelerate our simulations we should use this script to see how large we can push our simulations.

Add Cahn-Hilliard Float32 Example

---

src/simulation.jl
test/simulation.jl
test/simulation_core.jl

Generate sum([...]) for large vectors

---

src/simulation.jl

Advantages:
This works whether the component you want to change in a ComponentArray/NamedTuple is an array or not,
e.g. you can have `p = ComponentArray(k= 1.0)` or `p = ComponentArray(k = [1.0])` and it should work.

change getproperty to setproperty! in simulation

---

src/simulation.jl
test/simulation.jl
test/simulation_core.jl

Tests pass. Are there any other downstream consequences to renaming variables, e.g. `du` -> `__du__` this way?

proposing fix by changing variable names

---

src/simulation.jl
test/simulation.jl
test/simulation_core.jl

Currently, when compiling a Decapode, certain chains of matrix operations are pre-multiplied into single matrices. This cuts down on the number of matrix-vector multiplications in generated simulation code.
However the pre-multiplication of matrix operators can cause issues for certain autodiff implementations.
So, this PR adds a keyword argument to `gensim` that controls this behavior.

Add keyword argument for contract operators, clean simulation pipeline

---

src/operators.jl
test/operators.jl
test/runtests.jl

This is a tiny PR that uses a bool in `open_operators!` instead of an index, just to be explicit. No behavior should change.
This might be a rare opportunity to use a fall-through switch statement, since all but one case returns true. But of course that's not completely necessary.
We have discovered that some `open_operators` tests were lost during the `DiagrammaticEquations` split, and those are now recovered in this PR.

Use bool flag in open_operators!

---

examples/chemistry/gray_scott.jl

Updates the Gray-Scott example with boundary conditions and constants to produce cool looking behavior. This should probably be turned into a doc page that can showcase another example of Decapodes working with well-known physics as well as boundary condition implementations.

Add Gray-Scott doc page

---

.buildkite/build_docs.sh
.buildkite/pipeline.yml
.buildkite/run_tests.sh

This closes out a long-standing need to make Buildkite pipelines dynamic and GPU-enabled for Decapodes. Pipelines are imported from AlgebraicJulia `.github` repository but can be customized, like in [CombinatorialSpaces](https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/blob/cm/buildkite/.buildkite/pipeline.yml)
:construction: 
[This build](https://buildkite.com/algebraicjulia/decapodes/builds/720#01943711-8711-44ef-b7e1-75e2f1c57aff) works but [this most recent rebuild](https://buildkite.com/algebraicjulia/decapodes/builds/731#01946a9c-923c-4178-936c-e871d08a4a84) does not, attributed to a "curl error code 60."

Adding Dynamic Buildkite Pipeline

---

docs/src/ice_dynamics/ice_dynamics.md
src/operators.jl
src/simulation.jl

[CombinatorialSpaces PR 136](https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/pull/136) upstreamed and tested a 1D primal-primal sharp operation, as well as a new 1D primal-dual sharp operation.
This PR adds internal bindings for the Decapodes code emission for these operators. The superscripting scheme for these operators mirrors those for 2D. This is tested in the documentation via the Ice Dynamics page.

Add wrappers for 1D sharps

---

docs/src/overview/overview.md

The final recording is using the wrong solution object and thus only shows the diffusion physics. I've updated this to have it instead use the diff-adv physics.

Fix overview video
